# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formUi.ui'
#
# Created: Tue Feb 21 16:32:08 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(392, 300)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 400, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.pushButtonTab1Go = QtGui.QPushButton(self.tab)
        self.pushButtonTab1Go.setGeometry(QtCore.QRect(150, 170, 75, 23))
        self.pushButtonTab1Go.setObjectName("pushButtonTab1Go")
        self.pushButtonTab1Tbl = QtGui.QPushButton(self.tab)
        self.pushButtonTab1Tbl.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.pushButtonTab1Tbl.setObjectName("pushButtonTab1Tbl")
        self.pushButtonTab1Object = QtGui.QPushButton(self.tab)
        self.pushButtonTab1Object.setGeometry(QtCore.QRect(90, 90, 75, 23))
        self.pushButtonTab1Object.setObjectName("pushButtonTab1Object")
        self.pushButtonTab1Source = QtGui.QPushButton(self.tab)
        self.pushButtonTab1Source.setGeometry(QtCore.QRect(90, 60, 75, 23))
        self.pushButtonTab1Source.setObjectName("pushButtonTab1Source")
        self.lineEditTab1Object = QtGui.QLineEdit(self.tab)
        self.lineEditTab1Object.setGeometry(QtCore.QRect(180, 90, 130, 20))
        self.lineEditTab1Object.setObjectName("lineEditTab1Object")
        self.lineEditTab1Tbl = QtGui.QLineEdit(self.tab)
        self.lineEditTab1Tbl.setGeometry(QtCore.QRect(180, 120, 130, 20))
        self.lineEditTab1Tbl.setObjectName("lineEditTab1Tbl")
        self.lineEditTab1Source = QtGui.QLineEdit(self.tab)
        self.lineEditTab1Source.setGeometry(QtCore.QRect(180, 60, 130, 20))
        self.lineEditTab1Source.setObjectName("lineEditTab1Source")
        self.labelTab1Author = QtGui.QLabel(self.tab)
        self.labelTab1Author.setGeometry(QtCore.QRect(290, 230, 71, 20))
        self.labelTab1Author.setObjectName("labelTab1Author")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(290, 320, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonTab2Go = QtGui.QPushButton(self.tab_2)
        self.pushButtonTab2Go.setGeometry(QtCore.QRect(150, 190, 81, 23))
        self.pushButtonTab2Go.setObjectName("pushButtonTab2Go")
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 130, 61, 40))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButtonTab2Chs2Cht = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonTab2Chs2Cht.setChecked(True)
        self.radioButtonTab2Chs2Cht.setObjectName("radioButtonTab2Chs2Cht")
        self.verticalLayout_5.addWidget(self.radioButtonTab2Chs2Cht)
        self.radioButtonTab2Cht2Chs = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonTab2Cht2Chs.setObjectName("radioButtonTab2Cht2Chs")
        self.verticalLayout_5.addWidget(self.radioButtonTab2Cht2Chs)
        self.pushButtonTab2Object = QtGui.QPushButton(self.tab_2)
        self.pushButtonTab2Object.setGeometry(QtCore.QRect(90, 90, 75, 23))
        self.pushButtonTab2Object.setObjectName("pushButtonTab2Object")
        self.pushButtonTab2Source = QtGui.QPushButton(self.tab_2)
        self.pushButtonTab2Source.setGeometry(QtCore.QRect(90, 60, 75, 23))
        self.pushButtonTab2Source.setObjectName("pushButtonTab2Source")
        self.lineEditTab2Object = QtGui.QLineEdit(self.tab_2)
        self.lineEditTab2Object.setGeometry(QtCore.QRect(180, 90, 133, 20))
        self.lineEditTab2Object.setObjectName("lineEditTab2Object")
        self.lineEditTab2Source = QtGui.QLineEdit(self.tab_2)
        self.lineEditTab2Source.setGeometry(QtCore.QRect(180, 60, 133, 20))
        self.lineEditTab2Source.setObjectName("lineEditTab2Source")
        self.labelTab2Author = QtGui.QLabel(self.tab_2)
        self.labelTab2Author.setGeometry(QtCore.QRect(290, 230, 71, 20))
        self.labelTab2Author.setObjectName("labelTab2Author")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(320, 310, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 400, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 320, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButtonTab3Go = QtGui.QPushButton(self.tab_3)
        self.pushButtonTab3Go.setGeometry(QtCore.QRect(160, 210, 75, 23))
        self.pushButtonTab3Go.setObjectName("pushButtonTab3Go")
        self.pushButtonTab3Text2 = QtGui.QPushButton(self.tab_3)
        self.pushButtonTab3Text2.setGeometry(QtCore.QRect(90, 90, 75, 23))
        self.pushButtonTab3Text2.setObjectName("pushButtonTab3Text2")
        self.pushButtonTab3Text1 = QtGui.QPushButton(self.tab_3)
        self.pushButtonTab3Text1.setGeometry(QtCore.QRect(90, 60, 75, 23))
        self.pushButtonTab3Text1.setObjectName("pushButtonTab3Text1")
        self.lineEditTab3Text2 = QtGui.QLineEdit(self.tab_3)
        self.lineEditTab3Text2.setGeometry(QtCore.QRect(180, 90, 130, 20))
        self.lineEditTab3Text2.setObjectName("lineEditTab3Text2")
        self.lineEditTab3Index = QtGui.QLineEdit(self.tab_3)
        self.lineEditTab3Index.setGeometry(QtCore.QRect(130, 160, 191, 20))
        self.lineEditTab3Index.setObjectName("lineEditTab3Index")
        self.lineEditTab3Text1 = QtGui.QLineEdit(self.tab_3)
        self.lineEditTab3Text1.setGeometry(QtCore.QRect(180, 60, 130, 20))
        self.lineEditTab3Text1.setObjectName("lineEditTab3Text1")
        self.labelTab3IndexMessage = QtGui.QLabel(self.tab_3)
        self.labelTab3IndexMessage.setGeometry(QtCore.QRect(110, 185, 181, 16))
        self.labelTab3IndexMessage.setObjectName("labelTab3IndexMessage")
        self.pushButtonTab3Object = QtGui.QPushButton(self.tab_3)
        self.pushButtonTab3Object.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.pushButtonTab3Object.setObjectName("pushButtonTab3Object")
        self.lineEditTab3Object = QtGui.QLineEdit(self.tab_3)
        self.lineEditTab3Object.setGeometry(QtCore.QRect(180, 120, 130, 20))
        self.lineEditTab3Object.setObjectName("lineEditTab3Object")
        self.labelTab3Index = QtGui.QLabel(self.tab_3)
        self.labelTab3Index.setGeometry(QtCore.QRect(80, 160, 54, 21))
        self.labelTab3Index.setObjectName("labelTab3Index")
        self.labelTab3Author = QtGui.QLabel(self.tab_3)
        self.labelTab3Author.setGeometry(QtCore.QRect(290, 230, 71, 20))
        self.labelTab3Author.setObjectName("labelTab3Author")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lineEditTab4Source = QtGui.QLineEdit(self.tab_4)
        self.lineEditTab4Source.setGeometry(QtCore.QRect(180, 60, 130, 20))
        self.lineEditTab4Source.setObjectName("lineEditTab4Source")
        self.pushButtonTab4Source = QtGui.QPushButton(self.tab_4)
        self.pushButtonTab4Source.setGeometry(QtCore.QRect(90, 60, 75, 23))
        self.pushButtonTab4Source.setObjectName("pushButtonTab4Source")
        self.pushButtonTab4Object = QtGui.QPushButton(self.tab_4)
        self.pushButtonTab4Object.setGeometry(QtCore.QRect(90, 90, 75, 23))
        self.pushButtonTab4Object.setObjectName("pushButtonTab4Object")
        self.lineEditTab4Object = QtGui.QLineEdit(self.tab_4)
        self.lineEditTab4Object.setGeometry(QtCore.QRect(180, 90, 130, 20))
        self.lineEditTab4Object.setObjectName("lineEditTab4Object")
        self.pushButtonTab4Go = QtGui.QPushButton(self.tab_4)
        self.pushButtonTab4Go.setGeometry(QtCore.QRect(150, 170, 75, 23))
        self.pushButtonTab4Go.setObjectName("pushButtonTab4Go")
        self.labelTab4Author = QtGui.QLabel(self.tab_4)
        self.labelTab4Author.setGeometry(QtCore.QRect(290, 230, 71, 20))
        self.labelTab4Author.setObjectName("labelTab4Author")
        self.lineEditTab4Tbl = QtGui.QLineEdit(self.tab_4)
        self.lineEditTab4Tbl.setGeometry(QtCore.QRect(180, 120, 130, 20))
        self.lineEditTab4Tbl.setObjectName("lineEditTab4Tbl")
        self.pushButtonTab4Tbl = QtGui.QPushButton(self.tab_4)
        self.pushButtonTab4Tbl.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.pushButtonTab4Tbl.setObjectName("pushButtonTab4Tbl")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab1Go.setText(QtGui.QApplication.translate("MainWindow", "开始打包", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab1Tbl.setText(QtGui.QApplication.translate("MainWindow", "字库文件", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab1Object.setText(QtGui.QApplication.translate("MainWindow", "输出目录", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab1Source.setText(QtGui.QApplication.translate("MainWindow", "文本目录", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTab1Author.setText(QtGui.QApplication.translate("MainWindow", "作者：mp.s", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "文本打包", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab2Go.setText(QtGui.QApplication.translate("MainWindow", "开始转换", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonTab2Chs2Cht.setText(QtGui.QApplication.translate("MainWindow", "简转繁", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonTab2Cht2Chs.setText(QtGui.QApplication.translate("MainWindow", "繁转简", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab2Object.setText(QtGui.QApplication.translate("MainWindow", "输出目录", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab2Source.setText(QtGui.QApplication.translate("MainWindow", "文本目录", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTab2Author.setText(QtGui.QApplication.translate("MainWindow", "作者：烤鱼饼", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "简繁转换", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab3Go.setText(QtGui.QApplication.translate("MainWindow", "开始合并", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab3Text2.setText(QtGui.QApplication.translate("MainWindow", "文本2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab3Text1.setText(QtGui.QApplication.translate("MainWindow", "文本1", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTab3IndexMessage.setText(QtGui.QApplication.translate("MainWindow", "说明：支持多个标识符，用|分隔", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab3Object.setText(QtGui.QApplication.translate("MainWindow", "输出文本", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTab3Index.setText(QtGui.QApplication.translate("MainWindow", "标识符：", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTab3Author.setText(QtGui.QApplication.translate("MainWindow", "作者：烤鱼饼", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "文件合并", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab4Source.setText(QtGui.QApplication.translate("MainWindow", "文本目录", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab4Object.setText(QtGui.QApplication.translate("MainWindow", "输出位置", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab4Go.setText(QtGui.QApplication.translate("MainWindow", "开始统计", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTab4Author.setText(QtGui.QApplication.translate("MainWindow", "作者：mp.s", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTab4Tbl.setText(QtGui.QApplication.translate("MainWindow", "字库文件", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "字频统计", None, QtGui.QApplication.UnicodeUTF8))

